name: sphinx
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install --force-reinstall --upgrade pip 'sphinx==8.0.2'"
        build-command: "sphinx-build -b html . _build"
        docs-folder: "docs/"
